# docker-compose.yml
version: '3'
services:
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8888:8888'
